// Code generated by ent, DO NOT EDIT.

package store

import (
	"time"
)

const (
	// Label holds the string label denoting the store type in the database.
	Label = "store"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStoreCd holds the string denoting the store_cd field in the database.
	FieldStoreCd = "store_cd"
	// FieldCompanyCd holds the string denoting the company_cd field in the database.
	FieldCompanyCd = "company_cd"
	// FieldStoreName holds the string denoting the store_name field in the database.
	FieldStoreName = "store_name"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldLatitude holds the string denoting the latitude field in the database.
	FieldLatitude = "latitude"
	// FieldLongitude holds the string denoting the longitude field in the database.
	FieldLongitude = "longitude"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the store in the database.
	Table = "stores"
)

// Columns holds all SQL columns for store fields.
var Columns = []string{
	FieldID,
	FieldStoreCd,
	FieldCompanyCd,
	FieldStoreName,
	FieldAddress,
	FieldLatitude,
	FieldLongitude,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)
