// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// StoresColumns holds the columns for the "stores" table.
	StoresColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "store_cd", Type: field.TypeInt},
		{Name: "company_cd", Type: field.TypeInt},
		{Name: "store_name", Type: field.TypeString, SchemaType: map[string]string{"postgres": "varchar(50)"}},
		{Name: "address", Type: field.TypeString, SchemaType: map[string]string{"postgres": "varchar(255)"}},
		{Name: "latitude", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "decimal(7,4)"}},
		{Name: "longitude", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "decimal(7,4)"}},
		{Name: "created_at", Type: field.TypeTime},
	}
	// StoresTable holds the schema information for the "stores" table.
	StoresTable = &schema.Table{
		Name:       "stores",
		Columns:    StoresColumns,
		PrimaryKey: []*schema.Column{StoresColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "store_store_cd_company_cd",
				Unique:  true,
				Columns: []*schema.Column{StoresColumns[1], StoresColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		StoresTable,
	}
)

func init() {
}
