// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/MatsuoTakuro/my-template-connect-go/ent/schema"
	"github.com/MatsuoTakuro/my-template-connect-go/ent/store"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	storeFields := schema.Store{}.Fields()
	_ = storeFields
	// storeDescCreatedAt is the schema descriptor for created_at field.
	storeDescCreatedAt := storeFields[7].Descriptor()
	// store.DefaultCreatedAt holds the default value on creation for the created_at field.
	store.DefaultCreatedAt = storeDescCreatedAt.Default.(func() time.Time)
}
