// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MatsuoTakuro/my-template-connect-go/ent/predicate"
	"github.com/MatsuoTakuro/my-template-connect-go/ent/store"
)

// StoreUpdate is the builder for updating Store entities.
type StoreUpdate struct {
	config
	hooks    []Hook
	mutation *StoreMutation
}

// Where appends a list predicates to the StoreUpdate builder.
func (su *StoreUpdate) Where(ps ...predicate.Store) *StoreUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetStoreCd sets the "store_cd" field.
func (su *StoreUpdate) SetStoreCd(i int) *StoreUpdate {
	su.mutation.ResetStoreCd()
	su.mutation.SetStoreCd(i)
	return su
}

// AddStoreCd adds i to the "store_cd" field.
func (su *StoreUpdate) AddStoreCd(i int) *StoreUpdate {
	su.mutation.AddStoreCd(i)
	return su
}

// SetCompanyCd sets the "company_cd" field.
func (su *StoreUpdate) SetCompanyCd(i int) *StoreUpdate {
	su.mutation.ResetCompanyCd()
	su.mutation.SetCompanyCd(i)
	return su
}

// AddCompanyCd adds i to the "company_cd" field.
func (su *StoreUpdate) AddCompanyCd(i int) *StoreUpdate {
	su.mutation.AddCompanyCd(i)
	return su
}

// SetStoreName sets the "store_name" field.
func (su *StoreUpdate) SetStoreName(s string) *StoreUpdate {
	su.mutation.SetStoreName(s)
	return su
}

// SetAddress sets the "address" field.
func (su *StoreUpdate) SetAddress(s string) *StoreUpdate {
	su.mutation.SetAddress(s)
	return su
}

// SetLatitude sets the "latitude" field.
func (su *StoreUpdate) SetLatitude(f float64) *StoreUpdate {
	su.mutation.ResetLatitude()
	su.mutation.SetLatitude(f)
	return su
}

// AddLatitude adds f to the "latitude" field.
func (su *StoreUpdate) AddLatitude(f float64) *StoreUpdate {
	su.mutation.AddLatitude(f)
	return su
}

// SetLongitude sets the "longitude" field.
func (su *StoreUpdate) SetLongitude(f float64) *StoreUpdate {
	su.mutation.ResetLongitude()
	su.mutation.SetLongitude(f)
	return su
}

// AddLongitude adds f to the "longitude" field.
func (su *StoreUpdate) AddLongitude(f float64) *StoreUpdate {
	su.mutation.AddLongitude(f)
	return su
}

// Mutation returns the StoreMutation object of the builder.
func (su *StoreUpdate) Mutation() *StoreMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *StoreUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, StoreMutation](ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *StoreUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *StoreUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *StoreUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *StoreUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   store.Table,
			Columns: store.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: store.FieldID,
			},
		},
	}
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.StoreCd(); ok {
		_spec.SetField(store.FieldStoreCd, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedStoreCd(); ok {
		_spec.AddField(store.FieldStoreCd, field.TypeInt, value)
	}
	if value, ok := su.mutation.CompanyCd(); ok {
		_spec.SetField(store.FieldCompanyCd, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedCompanyCd(); ok {
		_spec.AddField(store.FieldCompanyCd, field.TypeInt, value)
	}
	if value, ok := su.mutation.StoreName(); ok {
		_spec.SetField(store.FieldStoreName, field.TypeString, value)
	}
	if value, ok := su.mutation.Address(); ok {
		_spec.SetField(store.FieldAddress, field.TypeString, value)
	}
	if value, ok := su.mutation.Latitude(); ok {
		_spec.SetField(store.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.AddedLatitude(); ok {
		_spec.AddField(store.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.Longitude(); ok {
		_spec.SetField(store.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.AddedLongitude(); ok {
		_spec.AddField(store.FieldLongitude, field.TypeFloat64, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{store.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// StoreUpdateOne is the builder for updating a single Store entity.
type StoreUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StoreMutation
}

// SetStoreCd sets the "store_cd" field.
func (suo *StoreUpdateOne) SetStoreCd(i int) *StoreUpdateOne {
	suo.mutation.ResetStoreCd()
	suo.mutation.SetStoreCd(i)
	return suo
}

// AddStoreCd adds i to the "store_cd" field.
func (suo *StoreUpdateOne) AddStoreCd(i int) *StoreUpdateOne {
	suo.mutation.AddStoreCd(i)
	return suo
}

// SetCompanyCd sets the "company_cd" field.
func (suo *StoreUpdateOne) SetCompanyCd(i int) *StoreUpdateOne {
	suo.mutation.ResetCompanyCd()
	suo.mutation.SetCompanyCd(i)
	return suo
}

// AddCompanyCd adds i to the "company_cd" field.
func (suo *StoreUpdateOne) AddCompanyCd(i int) *StoreUpdateOne {
	suo.mutation.AddCompanyCd(i)
	return suo
}

// SetStoreName sets the "store_name" field.
func (suo *StoreUpdateOne) SetStoreName(s string) *StoreUpdateOne {
	suo.mutation.SetStoreName(s)
	return suo
}

// SetAddress sets the "address" field.
func (suo *StoreUpdateOne) SetAddress(s string) *StoreUpdateOne {
	suo.mutation.SetAddress(s)
	return suo
}

// SetLatitude sets the "latitude" field.
func (suo *StoreUpdateOne) SetLatitude(f float64) *StoreUpdateOne {
	suo.mutation.ResetLatitude()
	suo.mutation.SetLatitude(f)
	return suo
}

// AddLatitude adds f to the "latitude" field.
func (suo *StoreUpdateOne) AddLatitude(f float64) *StoreUpdateOne {
	suo.mutation.AddLatitude(f)
	return suo
}

// SetLongitude sets the "longitude" field.
func (suo *StoreUpdateOne) SetLongitude(f float64) *StoreUpdateOne {
	suo.mutation.ResetLongitude()
	suo.mutation.SetLongitude(f)
	return suo
}

// AddLongitude adds f to the "longitude" field.
func (suo *StoreUpdateOne) AddLongitude(f float64) *StoreUpdateOne {
	suo.mutation.AddLongitude(f)
	return suo
}

// Mutation returns the StoreMutation object of the builder.
func (suo *StoreUpdateOne) Mutation() *StoreMutation {
	return suo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *StoreUpdateOne) Select(field string, fields ...string) *StoreUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Store entity.
func (suo *StoreUpdateOne) Save(ctx context.Context) (*Store, error) {
	return withHooks[*Store, StoreMutation](ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *StoreUpdateOne) SaveX(ctx context.Context) *Store {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *StoreUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *StoreUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *StoreUpdateOne) sqlSave(ctx context.Context) (_node *Store, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   store.Table,
			Columns: store.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: store.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Store.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, store.FieldID)
		for _, f := range fields {
			if !store.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != store.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.StoreCd(); ok {
		_spec.SetField(store.FieldStoreCd, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedStoreCd(); ok {
		_spec.AddField(store.FieldStoreCd, field.TypeInt, value)
	}
	if value, ok := suo.mutation.CompanyCd(); ok {
		_spec.SetField(store.FieldCompanyCd, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedCompanyCd(); ok {
		_spec.AddField(store.FieldCompanyCd, field.TypeInt, value)
	}
	if value, ok := suo.mutation.StoreName(); ok {
		_spec.SetField(store.FieldStoreName, field.TypeString, value)
	}
	if value, ok := suo.mutation.Address(); ok {
		_spec.SetField(store.FieldAddress, field.TypeString, value)
	}
	if value, ok := suo.mutation.Latitude(); ok {
		_spec.SetField(store.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.AddedLatitude(); ok {
		_spec.AddField(store.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.Longitude(); ok {
		_spec.SetField(store.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.AddedLongitude(); ok {
		_spec.AddField(store.FieldLongitude, field.TypeFloat64, value)
	}
	_node = &Store{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{store.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
