name: test
on:
  push:
    branches: [ main ]
jobs:
  golangci:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: sa
          POSTGRES_DB: template-db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest]
    name: test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: go test
        run: bash -c 'go test -v -race -shuffle=on -covermode=atomic ./...'
